### PR TITLE
Add optional support for completely customized animations via delegate

### PR DESCRIPTION
**Pull request by adly-holler**

### CODE REVIEW

**Comment by stanislaw** [comment]
@adly-holler, thanks for contribution! I've merged your other PR. Before merging this one I need some time to review it.

@itsbonczek, do you have any thoughts about this PR?

**Comment by itsbonczek** [comment]
Hi! Sorry for the delay on this. This is a really great, simple addition to the codebase. Nice work, @adly-holler! 

One thing before merging. The lines of code you introduced are a bit long. Do you mine breaking up the method calls at the parameters? Future git-diff viewers will thank you :smile: 

Thanks again!

**Comment by adly-holler** [comment]
@itsbonczek Hey you're welcome – you've made a great framework and I'm glad I could give something back. I've made those changes

**Comment by itsbonczek** [comment]
Looks good @adly-holler!

**Pull request merged**
